# Generated by Django 5.1.4 on 2025-04-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_productimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["user__first_name", "user__last_name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
    ]
